import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 10

normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1
startup_mode = "Windowed"

[window.padding]
x = 10
y = 10
