
[env]
TERM = "xterm-256color"

[font]
size = 10

normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }

[window]
decorations = "none"
dynamic_padding = true
opacity = 1
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" }
]

[general]
import = [
    "~/.config/alacritty/gruvbox_dark.toml"
]
